# Generated by Django 3.1.1 on 2020-09-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ('name',), 'verbose_name': 'test verbose Name', 'verbose_name_plural': 'catagories'},
        ),
    ]
